# Generated by Django 5.2.4 on 2025-07-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_article_comment_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='video',
            new_name='video_id',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='user_id',
        ),
    ]
