# Generated by Django 5.2.4 on 2025-07-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_user_article_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
