# Generated by Django 5.2.4 on 2025-07-16 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_user_id_article_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Наименование поста должно быть не меньше 5 симоволов'), django.core.validators.MaxLengthValidator(255, message='Наименование поста должно быть не больше 255 симоволов')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Наименование видео должно быть не больше 255 символов', 'min_length': 'Наименование видео должно быть не меньше 5 символов'}, max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
