# Generated by Django 5.2.4 on 2025-07-16 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_article_article_alter_article_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Наименование видео должно быть не больше 255 символов', 'min_length': 'Наименование видео должно быть не меньше 5 символов'}, max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Наименование видео должно быть не меньше 5 символов'), django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
